---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: awx.awx
      - name: azure.azcollection
        version: ">=2.1.0"
      - name: amazon.aws
      - name: theforeman.foreman
      - name: google.cloud
      - name: openstack.cloud
      - name: community.vmware
      - name: ovirt.ovirt
      - name: kubernetes.core
      - name: ansible.posix
      - name: ansible.windows
      - name: redhatinsights.insights
  system: |
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    make [platform:rpm compile]
    iproute [platform:rpm compile]
    iptables [platform:rpm compile]
    openssl-devel [platform:rpm compile]
    iproute [platform:rpm]
    iptables [platform:rpm]
    iputils [platform:rpm]
    procps-ng [platform:rpm]

  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl

# copy your hook into the EE
additional_build_files:
  - src: hooks/pre_run.sh
    dest: hooks
  - src: scripts/entrypoint.sh
    dest: scripts


additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
  # Install border0 binary
    - ADD https://download.border0.com/linux_amd64/border0 /bin/border0
    - RUN mkdir -p /usr/local/bin
    - COPY _build/hooks/pre_run.sh /usr/local/bin/pre_run.sh
    - COPY _build/scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
    - RUN chmod +x /bin/border0
    - RUN chmod +x /usr/local/bin/*
    # defaults
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    - ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
