---
- name: Check local networking and Border0 peers
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cmds:
      - { name: "Border0 version",        cmd: "border0 version check" }
      - { name: "Border0 node peer debug",        cmd: "border0 node debug peers" }
      - { name: "Border0 node state",        cmd: "border0 node state show" }

  tasks:

    - name: Run all diagnostic commands
      ansible.builtin.command: "{{ item.cmd }}"
      register: result
      loop: "{{ cmds }}"
      loop_control:
        label: "{{ item.name }}"
      retries: 9
      delay: 30
      until: result is succeeded
      ignore_errors: true

    - name: Display outputs
      ansible.builtin.debug:
        msg: |
          === {{ item.item.name }} ===
          {% if item.rc == 0 %}
          {{ item.stdout }}
          {% else %}
          ❌ FAILED (rc={{ item.rc }}, attempts={{ item.attempts | default(1) }}):
          {{ item.stderr }}
          {% endif %}
      loop: "{{ result.results }}"

    - name: Show final summary
      ansible.builtin.debug:
        msg: |
          {% set ns = namespace(passed=0, failed=0) %}
          {% for item in result.results %}
          {% if item.rc == 0 %}
          {% set ns.passed = ns.passed + 1 %}
          {% else %}
          {% set ns.failed = ns.failed + 1 %}
          {% endif %}
          {% endfor %}
          
          === SUMMARY ===
          ✅ Passed: {{ ns.passed }}
          ❌ Failed: {{ ns.failed }}
          📊 Total:  {{ result.results | length }}
          
          {% if ns.failed > 0 %}
          ⚠️  Some commands failed but were ignored to show all results
          {% endif %}

